### ISSUE TITLE
Packed Sequences

### ISSUE THREAD

**Issue by Algomancer** [lucidrains/meshgpt-pytorch#20]
I have an internal version of a similar architecture to meshgpt (with down sampling with a graph seanet/encodec style encoder/decoder
 for shorter sequences and a few other changes, will open source when I have completed weights).

Was just wondering why you are not using packed sequences for the vertex/face inputs to your autoencoder. That way its a bit nicer to handle dynamic number of vertices and faces in a batch.

**Comment by fire** [comment]
I'm not the maintainer of this repository, but I'm curious what you mean by packed sequences.

**Comment by Algomancer** [comment]
Typically when dealing with graphs or other heterogeneous data structures (like meshes) we represent things as a packed sequence, which is just flattened over the batches. You basically store an index table and flatten the sequence length into (batch * seq_len, features). 
![batch_modes](https://github.com/lucidrains/meshgpt-pytorch/assets/13579432/e3c79945-8daf-4262-b1ce-a7f5a26e94cc)

**Comment by lucidrains** [comment]
@Algomancer hey Adam! only because i've never used it

this is actually my first time using graph convs

i have [another project](https://github.com/lucidrains/chroma-pytorch) where i will need to use graph convs, so maybe i will give packed sequences a try there and once it is working port it over here. kind of "if it aint broke don't fix it" at the moment
